# Generated by Django 3.0.7 on 2020-06-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comment_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='news_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news_id', to='news.New'),
            preserve_default=False,
        ),
    ]
