# Generated by Django 3.0.7 on 2020-06-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment_news_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='news_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.New'),
            preserve_default=False,
        ),
    ]
