# Generated by Django 3.0.7 on 2020-06-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='temp_user',
        ),
    ]
